fix(action): simplify fast-apt-mirror.sh setup

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -19,9 +19,6 @@ inputs:
   exclude-current:  { default: "false", description: "Don't include the current APT mirror in the speed tests." }
   country:          { default:      "", description: "The country code to use for selecting mirrors. NOTE: Only applies to Ubuntu based distros. Defaults to http://mirrors.ubuntu.com/mirrors.txt" }
 
-  repo-name:   { default: "vegardit/fast-apt-mirror.sh", description: "Repository containing the fast-apt-mirror.sh script" }
-  repo-branch: { default: "v1", description: "Version (i.e. github branch) of the fast-apt-mirror.sh script to use" }
-
 runs:
   using: "composite"
   steps:
@@ -45,20 +42,16 @@ runs:
         echo 'APT::Acquire::Retries "3";' | sudo tee /etc/apt/apt.conf.d/80-acquire-retries
 
         if [[ "${{ env.ACT }}" != "true" ]]; then
-          # Workaround to avoid sporadic connectivity issues "Could not connect to azure.archive.ubuntu.com:80"
-          # see https://github.com/actions/runner-images/issues/675
-          # see https://github.com/actions/runner-images/issues/704
-          if (set -x; curl -sSfL --retry 3 --max-time 6 https://raw.githubusercontent.com/${{ inputs.repo-name }}/${{ inputs.repo-branch }}/fast-apt-mirror.sh -o $HOME/fast-apt-mirror.sh); then
-            bash $HOME/fast-apt-mirror.sh find --apply --verbose \
-              --healthchecks ${{ inputs.healthchecks }} \
-              --ignore-sync-state \
-              --speedtests   ${{ inputs.speedtests }} \
-              --parallel     ${{ inputs.parallel }} \
-              --sample-size  ${{ inputs.sample-size }} \
-              --sample-time  ${{ inputs.sample-time }} \
-              --country      "$COUNTRY_CODE" \
-              ${{ inputs.exclude-current == 'true' && '--exclude-current' || '' }}
-          fi || exit 0 # don't fail action if APT mirror detection failed for whatever reason
+          bash "$GITHUB_ACTION_PATH/fast-apt-mirror.sh" find --apply --verbose \
+            --healthchecks ${{ inputs.healthchecks }} \
+            --ignore-sync-state \
+            --speedtests   ${{ inputs.speedtests }} \
+            --parallel     ${{ inputs.parallel }} \
+            --sample-size  ${{ inputs.sample-size }} \
+            --sample-time  ${{ inputs.sample-time }} \
+            --country      "$COUNTRY_CODE" \
+            ${{ inputs.exclude-current == 'true' && '--exclude-current' || '' }} \
+            || exit 0 # don't fail action if APT mirror detection failed for whatever reason
         fi
 
         # refresh pkg cache if it does not exist or is older than 60min.
